FROM ubuntu
ARG CHANNEL=stable
ARG VERSION=14.6.47
RUN apt-get update -y && \
    apt-get install wget -y && \
    apt-get install awscli -y
RUN wget "http://packages.chef.io/files/${CHANNEL}/chef/${VERSION}/el/6/chef-${VERSION}-1.el6.x86_64.rpm" -O /tmp/chef-client.rpm && \
    rpm2cpio /tmp/chef-client.rpm | cpio -idmv && \
    rm -rf /tmp/chef-client.rpm

ADD solo_config/solo.rb /etc/chef/solo.rb
WORKDIR /var/chef/cookbooks
